### ISSUE TITLE
Remove --disable-network a possibility?

### ISSUE THREAD

**Issue by wsfulton** [conda-forge/xerces-c-feedstock#17]
Is there a reason that xerces-c is built without network support on Linux? I need the network support enabled. Would a patch to remove `--disable-network` at
https://github.com/conda-forge/xerces-c-feedstock/blob/5ddb7a19683487d0ea14e2aaa6fd98ca0acb1aec/recipe/build.sh#L3
be considered (plus whatever else is needed to get it to build)?

**Comment by ocefpaf** [comment]
> Is there a reason that xerces-c is built without network support on Linux? I need the network support enabled. Would a patch to remove `--disable-network` at
> [xerces-c-feedstock/recipe/build.sh](https://github.com/conda-forge/xerces-c-feedstock/blob/5ddb7a19683487d0ea14e2aaa6fd98ca0acb1aec/recipe/build.sh#L3)
> 
> Line 3 in [5ddb7a1](/conda-forge/xerces-c-feedstock/commit/5ddb7a19683487d0ea14e2aaa6fd98ca0acb1aec)
> 
>  ./configure --prefix=$PREFIX --with-icu --disable-network 
> 
> be considered (plus whatever else is needed to get it to build)?

I don't really know that than entails but it is worth a try. Do you want to send a PR?

**Comment by ocefpaf** [comment]
Done in #18
