### ISSUE TITLE
c-files missing on windows

### ISSUE THREAD

**Issue by kmuehlbauer** [conda-forge/xerces-c-feedstock#2]
As seen [here](https://github.com/conda-forge/gdal-feedstock/pull/92) there is an issue with `xerces-c` missing some c-files  on windows.

The latest default `xerces-c` bundles these c-files, while here they are [excluded from packaging](https://github.com/conda-forge/xerces-c-feedstock/blob/master/recipe/bld.bat#L45).

ping @ocefpaf

**Comment by kmuehlbauer** [comment]
closed by #3

**Comment by ocefpaf** [comment]
Thanks @kmuehlbauer!
