### ISSUE TITLE
xerces-c links against system provided libnsl

### ISSUE THREAD

**Issue by akrherz** [conda-forge/xerces-c-feedstock#29]
As pointed out on [conda-forge/rasterio-feedstock#220](https://github.com/conda-forge/rasterio-feedstock/issues/220#issuecomment-933570033), this recipe may need to be updated to build with conda-forge provided `libnsl`.  Indeed, on my linux 64 python3.8 install (centos 8).

```
ldd /opt/miniconda3/envs/prod/lib/libxerces-c-3.2.so | grep nsl
	libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f7abe75e000)
```

**Comment by gillins** [comment]
Thanks @akrherz are you happy to submit a PR with the change?

**Comment by akrherz** [comment]
> Thanks @akrherz are you happy to submit a PR with the change?

I do not fully understand why this is happening, so if somebody else knows the proper fix, go for it!

**Comment by izahn** [comment]
It will link against the new conda-forge `libnsl` there too, e.g., on CentOS 7:

```
[root@a4cc198ea638 /]# curl -L https://github.com/conda-forge/miniforge/releases/download/4.10.3-6/Mambaforge-4.10.3-6-Linux-x86_64.sh > mf.sh

<SNIP>

[root@a4cc198ea638 /]# bash ./mf.sh 

Welcome to Mambaforge 4.10.3-6

<SNIP>

[root@a4cc198ea638 /]# bash
(base) [root@a4cc198ea638 /]# mamba create -n tst1 xerces-c

Looking for: ['xerces-c']

<SNIP>

(base) [root@a4cc198ea638 /]# ldd ~/mambaforge/envs/tst1/lib/libxerces-c-3.2.so | grep nsl ## the current conda-forge package, cos7
        libnsl.so.1 => /lib64/libnsl.so.1 (0x00007f0a35fa2000)
(base) [root@a4cc198ea638 /]# mamba create -n tst2 -c izahn xerces-c

<SNIP>

(base) [root@a4cc198ea638 /]# ldd ~/mambaforge/envs/tst2/lib/libxerces-c-3.2.so | grep nsl ## rebuilt with libnsl, cos7
        libnsl.so.3 => /root/mambaforge/envs/tst2/lib/./libnsl.so.3 (0x00007fb31284c000)
```
This is good because it provides consistency and make it more likely that the package will work on a variety of Linux distributions.

**Comment by izahn** [comment]
> Thanks @izahn ! I didn't spend the time to figure out the mechanics of how `libnsl` worked and what would happen with such a build change on non-RHEL linuxes that don't have this 'problem' ?

Note also that this isn't just a RHEL 8 problem, it affects most recent Linux distributions.
